"use client";

import { CheckCircle2, ExternalLink, Eye, EyeOff, KeyRound, ShieldCheck, Sparkles, Trash2 } from "lucide-react";
import { Avatar, type ShellUser } from "@/components/app-shell";
import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";
import { toast } from "sonner";
import { EnginePicker } from "@/components/ai/engine-picker";
import { LocalModelPanel } from "@/components/ai/local-model";
import { Button, ConfirmDialog, Input, Label, PageHeader, Panel, cn } from "@/components/ui";
import { CLOUD_PROVIDERS, PROVIDER_INFO, type AiProvider, type AiStatus, type CloudProvider } from "@/lib/ai/providers";
import { api, errorMessage } from "@/lib/client";

export function SettingsView({ initialStatus, user }: { initialStatus: AiStatus; user: ShellUser }) {
  const router = useRouter();
  const [status, setStatus] = useState(initialStatus);
  const [savingDefault, setSavingDefault] = useState(false);
  const [toRemove, setToRemove] = useState<CloudProvider | null>(null);
  const [removing, setRemoving] = useState(false);

  async function chooseDefault(provider: AiProvider) {
    if (provider === status.provider) return;
    setSavingDefault(true);
    try {
      setStatus(await api<AiStatus>("/api/settings/ai", { method: "PATCH", json: { provider } }));
      toast.success(`${PROVIDER_INFO[provider].label} is now your default AI engine`);
      router.refresh();
    } catch (err) {
      toast.error(errorMessage(err));
    } finally {
      setSavingDefault(false);
    }
  }

  async function remove() {
    if (!toRemove) return;
    setRemoving(true);
    try {
      setStatus(await api<AiStatus>(`/api/settings/ai/${toRemove}`, { method: "DELETE" }));
      toast.success("Key removed from this browser");
      setToRemove(null);
      router.refresh();
    } catch (err) {
      toast.error(errorMessage(err));
    } finally {
      setRemoving(false);
    }
  }

  return (
    <div className="max-w-3xl">
      <PageHeader eyebrow="Account" title="Settings" description="Your profile and the AI engine used to generate flashcards." />

      <Panel className="mb-5 flex items-center gap-4 p-5">
        <Avatar name={user.name} image={user.image} className="size-12 text-sm" />
        <div className="min-w-0">
          <p className="font-serif text-xl font-semibold text-heading">{user.name}</p>
          <p className="truncate text-[13px] text-ink-muted">{user.email}</p>
        </div>
      </Panel>

      <Panel className="p-5 sm:p-6">
        <div className="flex items-start gap-4">
          <div className="grid size-11 shrink-0 place-items-center rounded-full bg-highlight text-on-highlight">
            <Sparkles className="size-5" />
          </div>
          <div className="min-w-0 flex-1">
            <h2 className="font-serif text-[22px] font-semibold text-heading">AI engine</h2>
            <p className="mt-1 text-[13px] text-ink-muted">
              By default flashcards are generated by a local AI that runs in your browser, for free. With your own API key you can use Gemini, Claude,
              OpenAI or OpenRouter instead: usually faster and more accurate on long materials and images. You can also pick the engine for each
              generation.
            </p>
          </div>
        </div>
        <div className={cn("mt-5", savingDefault && "pointer-events-none opacity-70")}>
          <Label>Default engine</Label>
          <EnginePicker status={status} value={status.provider} onChange={chooseDefault} />
        </div>
        <div className="mt-5">
          <LocalModelPanel />
        </div>
      </Panel>

      <h2 className="mt-8 mb-3 flex items-center gap-2 font-serif text-[20px] font-semibold text-heading">
        <KeyRound className="size-5 text-ink-muted" /> API keys <span className="font-sans text-xs font-normal text-ink-faint">optional</span>
      </h2>
      <div className="space-y-4">
        {CLOUD_PROVIDERS.map((p) => (
          <ProviderKeyPanel key={p} provider={p} status={status} onSaved={(s) => { setStatus(s); router.refresh(); }} onRemove={() => setToRemove(p)} />
        ))}
      </div>

      <Panel className="mt-5 bg-sunken p-5 sm:p-6">
        <h3 className="flex items-center gap-2 font-serif text-lg font-semibold text-heading">
          <ShieldCheck className="size-4 text-accent" /> Privacy
        </h3>
        <ul className="mt-3 list-disc space-y-1.5 pl-5 text-[13px] text-ink-muted">
          <li>With the local AI the materials are processed on your device and nothing is sent to an AI provider.</li>
          <li>API keys stay only in this browser, in an encrypted cookie that page scripts cannot read.</li>
          <li>The server only uses a key during your generations and never stores it in the database; generations use your quota, not the class’s.</li>
          <li>Signing out removes the keys: you’ll need to enter them again after signing back in.</li>
        </ul>
      </Panel>

      <ConfirmDialog
        open={toRemove !== null}
        onClose={() => setToRemove(null)}
        onConfirm={remove}
        loading={removing}
        title="Remove the key?"
        description={
          toRemove && status.provider === toRemove
            ? `${PROVIDER_INFO[toRemove].label} is your default engine: new generations will use the local AI.`
            : "You can add it again at any time."
        }
        confirmLabel="Remove"
      />
    </div>
  );
}

function ProviderKeyPanel({
  provider,
  status,
  onSaved,
  onRemove,
}: {
  provider: CloudProvider;
  status: AiStatus;
  onSaved: (s: AiStatus) => void;
  onRemove: () => void;
}) {
  const info = PROVIDER_INFO[provider];
  const current = status.cloud[provider];
  const [apiKey, setApiKey] = useState("");
  const [model, setModel] = useState(current.model === current.defaultModel ? "" : current.model);
  const [show, setShow] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const modelChanged = model.trim() !== (current.model === current.defaultModel ? "" : current.model);

  async function save(e: FormEvent) {
    e.preventDefault();
    setSaving(true);
    setError(null);
    try {
      const res = await api<AiStatus>(`/api/settings/ai/${provider}`, {
        method: "PUT",
        json: { ...(apiKey.trim() ? { apiKey: apiKey.trim() } : {}), model: model.trim() },
      });
      onSaved(res);
      setApiKey("");
      setShow(false);
      toast.success(`${info.label}: key verified and saved`);
    } catch (err) {
      setError(errorMessage(err));
    } finally {
      setSaving(false);
    }
  }

  return (
    <Panel className="p-5">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="min-w-0">
          <h3 className="font-serif text-lg font-semibold text-heading">{info.label}</h3>
          <p className="text-xs text-ink-muted">{info.vendor}</p>
        </div>
        {current.configured ? (
          <div className="flex items-center gap-2">
            <span className="flex items-center gap-1.5 rounded-full bg-accent-soft px-2.5 py-1 text-xs font-semibold text-accent">
              <CheckCircle2 className="size-3.5" /> <span className="font-mono font-normal">{current.masked}</span>
            </span>
            <Button variant="ghost" size="sm" className="text-danger hover:text-danger" onClick={onRemove} aria-label={`Remove the ${info.label} key`}>
              <Trash2 className="size-4" />
            </Button>
          </div>
        ) : (
          <a href={info.keyUrl} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1.5 text-[13px] font-semibold text-accent hover:underline">
            {info.keyHelp} <ExternalLink className="size-3.5" />
          </a>
        )}
      </div>

      <form onSubmit={save} className="mt-4 grid gap-3 sm:grid-cols-[minmax(0,1fr)_200px]">
        <div>
          <Label htmlFor={`${provider}-key`}>{current.configured ? "Replace the key" : "API key"}</Label>
          <div className="relative">
            <Input
              id={`${provider}-key`}
              type={show ? "text" : "password"}
              autoComplete="off"
              spellCheck={false}
              placeholder={info.keyPlaceholder}
              className="pr-10 font-mono"
              value={apiKey}
              onChange={(e) => setApiKey(e.target.value)}
            />
            <button
              type="button"
              onClick={() => setShow((s) => !s)}
              className="absolute top-1/2 right-2 grid size-7 -translate-y-1/2 cursor-pointer place-items-center rounded-md text-ink-faint hover:text-ink"
              aria-label={show ? "Hide key" : "Show key"}
            >
              {show ? <EyeOff className="size-4" /> : <Eye className="size-4" />}
            </button>
          </div>
        </div>
        <div>
          <Label htmlFor={`${provider}-model`} hint="optional">
            Model
          </Label>
          <Input
            id={`${provider}-model`}
            autoComplete="off"
            spellCheck={false}
            placeholder={current.defaultModel}
            className="font-mono text-[13px]"
            value={model}
            onChange={(e) => setModel(e.target.value)}
          />
        </div>
        <div className="flex items-center justify-end sm:col-span-2">
          <Button type="submit" size="sm" loading={saving} disabled={!apiKey.trim() && !(current.configured && modelChanged)}>
            Verify and save
          </Button>
        </div>
        {error && (
          <p role="alert" className="rounded-md bg-danger-soft px-3.5 py-2.5 text-sm text-on-danger-soft sm:col-span-2">
            {error}
          </p>
        )}
      </form>
    </Panel>
  );
}
